atey:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: produce
    username: root
    password: 160814
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRUrUozCyWWkEiQJTwq
    access-key-secret: HUEuxILo9tkuGuNvBgBFpBpbUHEQVN
    bucket-name: spring-tlias-start
  redis:
    host: localhost
    port: 6379
    password: 160814
    database: 9